image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - echo "> script start"
  - pwd


stages:
  - build

build:
  stage: build
  only:
    - main
  script:
    - echo "> build start"
    - chmod +x gradlew
    - ./gradlew build