variables:
  API1_PATH: "./api1/build/libs/api1-0.0.1-SNAPSHOT.jar"
  API2_PATH: "./api2/build/libs/api2-0.0.1-SNAPSHOT.jar"

image: gradle:alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - echo "> script start"
  - pwd


stages:
  - build
  - package

build:
  stage: build
  only:
    - main
  script:
    - echo "> build start"
    - chmod +x gradlew
    - ./gradlew build

docker-build:
  image: docker:latest
  stage: package
  services:
    - docker:dind
  variables:
    DOCKER_USER: "$DOCKER_USER"
    DOCKER_PW: "$DOCKER_PASSWORD"
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PW"
    - apk update && apk add git
  script:
    - docker-compose up -d