version: '3'

services:
  api1:
    build:
      context: ./api1
      dockerfile: Dockerfile
    container_name: api1
    ports:
      - '8080:8080'
    image: admin1125/api1:latest
  api2:
    build:
      context: ./api2
      dockerfile: Dockerfile
    container_name: api2
    ports:
      - '8081:8081'
    image: admin1125/api2:latest
